/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ReservasDAO;
import dto.ReservasDTO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import com.toedter.calendar.JDateChooser;
import controller.HuespedesDAO;
import dto.HuespedesDTO;
import java.awt.Component;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;


/**
 *
 * @author Edwin
 */
public class OpReservas extends javax.swing.JDialog {
    private String Mode = "";
    static private int id = 0;
    private reservas parent;
    private ReservasDTO dto;
    private ReservasDAO dao;
    private JDateChooser JTextField4;
    private JDateChooser JTextField5;
    
    public OpReservas(reservas parent, boolean modal, String mode, ReservasDTO DTO) {
        super(parent, modal);
        initComponents();
        
        cargarHuespedesEnComboBox(); 
        // Crear los JDateChooser
        JTextField4 = new JDateChooser();
        JTextField5 = new JDateChooser();
JTextField4.setBounds(205, 140, 165, 30);  // Ajusta la posición y el tamaño según sea necesario
JTextField5.setBounds(205, 170, 165, 30);  // Ajusta la posición y el tamaño según sea necesario
jComboBox1.setBounds(205, 170, 165, 30);

        // Ajustar el formato de las fechas
        JTextField4.setDateFormatString("dd-MM-yyyy");
        JTextField5.setDateFormatString("dd-MM-yyyy");

        // Añadir los JDateChooser al panel
        jPanel1.add(JTextField4);
        jPanel1.add(JTextField5);

        this.Mode = mode;
        this.dto = DTO;  // Asegúrate de que 'dto' esté bien inicializado
        this.dao = new ReservasDAO();
        setLocationRelativeTo(null);
        this.parent = parent;     

        if (this.dto == null) {
            limpar(); // Limpiar campos si el DTO es nulo
        } else {
            this.id = dto.getId_reserva(); // Asignar el ID desde el DTO

            // Asignar valores a los campos de texto
            this.jTextField1.setText(Integer.toString(dto.getId_reserva()));
           //this.jTextField2.setText(Integer.toString(dto.getId_huesped()));
            this.jTextField3.setText(Integer.toString(dto.getId_habitacion()));

            // Usar SimpleDateFormat para dar formato a las fechas
            this.JTextField4.setDate(dto.getFecha_inicio());
            this.JTextField5.setDate(dto.getFecha_fin());

            this.jTextField6.setText(Integer.toString(dto.getActivo()));
        }

        AnchoCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservas");
        setResizable(false);

        jLabel1.setText("No. Reserva");

        jLabel2.setText("No. Huesped");

        jLabel3.setText("No. Habitacion");

        jLabel4.setText("F. Inicio");

        jLabel5.setText("F. Fin");

        jLabel6.setText("Activo");
        jLabel6.setToolTipText("");

        jTextField1.setText("jTextField1");

        jTextField3.setText("jTextField3");

        jTextField6.setText("jTextField6");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(45, 45, 45)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
        // Obtener las fechas desde los JDateChooser
        Date fechaInicio = JTextField4.getDate();
        Date fechaFin = JTextField5.getDate();

        // Validar si alguna de las fechas es nula
        if (fechaInicio == null || fechaFin == null) {
            throw new IllegalArgumentException("Las fechas no pueden estar vacías.");
        }

        // Convertir java.util.Date a java.sql.Date
        java.sql.Date sqlFechaInicio = new java.sql.Date(fechaInicio.getTime());
        java.sql.Date sqlFechaFin = new java.sql.Date(fechaFin.getTime());

        // Obtener el id_huesped seleccionado en el JComboBox
        String seleccionado = (String) jComboBox1.getSelectedItem();
        if (seleccionado != null) {
            // Extraer el id_huesped de la cadena seleccionada (asumiendo el formato "id_huesped - nombre")
            String[] partes = seleccionado.split(" - ");
            int idHuesped = Integer.parseInt(partes[0]); // El id_huesped es la primera parte
          
            // Verificar si el modo es INS o UPD
            if (Mode.equals("INS")) {
                // Crear un nuevo objeto DTO con los valores ingresados
                ReservasDTO nuevaReserva = new ReservasDTO();
                nuevaReserva.setId_reserva(Integer.parseInt(jTextField1.getText()));
                nuevaReserva.setId_huesped(idHuesped); // Asignamos el id_huesped seleccionado
                nuevaReserva.setId_habitacion(Integer.parseInt(jTextField3.getText()));
                nuevaReserva.setFecha_inicio(sqlFechaInicio);
                nuevaReserva.setFecha_fin(sqlFechaFin);
                nuevaReserva.setActivo(Integer.parseInt(jTextField6.getText()));

                // Llamar al método del DAO para insertar la nueva reserva
                dao.insert(nuevaReserva);
            } else if (Mode.equals("UPD")) {
                // Actualizar la reserva existente
                dto.setId_huesped(idHuesped); // Asignamos el id_huesped seleccionado
                dto.setId_habitacion(Integer.parseInt(jTextField3.getText()));
                dto.setFecha_inicio(sqlFechaInicio);
                dto.setFecha_fin(sqlFechaFin);
                dto.setActivo(Integer.parseInt(jTextField6.getText()));

                // Llamar al método del DAO para actualizar la reserva
                dao.update(dto);
            }

            // Cerrar el formulario después de guardar o actualizar
            this.dispose();
        } else {
            // En caso de que no se haya seleccionado un huésped
            throw new IllegalArgumentException("Debe seleccionar un huésped.");
        }
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Entrada", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed
private void cargarHuespedesEnComboBox() {
    // Crear instancia de HuespedesDAO para obtener los datos
    HuespedesDAO huespedesDAO = new HuespedesDAO();

    // Obtener la lista de HuespedesDTO desde el DAO
    List<HuespedesDTO> listaHuespedes = huespedesDAO.obtenerHuespedes();

    // Limpiar el JComboBox antes de agregar nuevos elementos
    jComboBox1.removeAllItems();

    // Llenar el JComboBox con los objetos HuespedesDTO completos
    for (HuespedesDTO huesped : listaHuespedes) {
        // Crear una cadena representando id_huesped y nombre
        String item = huesped.getId_huesped() + " - " + huesped.getNombre();
        jComboBox1.addItem(item); // Solo agregamos el String
    }

    // Configurar el renderizador para mostrar id_huesped y nombre
    jComboBox1.setRenderer(new DefaultListCellRenderer() {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            // Mostrar id_huesped y nombre
            return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        }
    });
}

private void obtenerHuespedSeleccionado() {
    // Obtener el texto seleccionado en el JComboBox (id_huesped - nombre)
    String seleccionado = (String) jComboBox1.getSelectedItem();

    if (seleccionado != null) {
        // Extraer el id_huesped de la cadena (suponiendo el formato "id_huesped - nombre")
        String[] partes = seleccionado.split(" - ");
        int idHuesped = Integer.parseInt(partes[0]);  // El id_huesped es la primera parte de la cadena
        System.out.println("Huésped seleccionado: " + idHuesped);
    }
}



 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new OpReservas().setVisible(true);
                
            }
        });
    }
    
    public void limpar()
    {
        this.jTextField1.setText("");
       // this.jTextField2.setText("");
        this.jTextField3.setText("");
        JTextField4.setDate(null);
JTextField5.setDate(null);

        //this.jTextField4.setText("");
       // this.jTextField5.setText("");
        this.jTextField6.setText("");
    }
        public void AnchoCampos()
    {
        this.jTextField1.setColumns(10);
      //  this.jTextField2.setColumns(10);
        this.jTextField3.setColumns(10);
        this.jTextField6.setColumns(10);
        jComboBox1.setPreferredSize(new java.awt.Dimension(125, 30));
    
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
