/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UsuariosDAO;
import dto.UsuariosDTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Usuarios;

/**
 *
 * @author Edwin
 */
public class usuarios extends javax.swing.JDialog {

    /**
     * Creates new form Usuarios
     */
    
    private DefaultTableModel modeloTabla;
    private UsuariosDAO usuariosDAO = new UsuariosDAO();
    private JFMenu parent;
    
    public usuarios(JFMenu parent, boolean modal) {
        super(parent, modal); 
        initComponents();
        setLocationRelativeTo(null);
        this.parent = parent;
        modeloTabla = (DefaultTableModel) jTable1.getModel();
        cargarDatos();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new usuarios().setVisible(true);
            }
        });
    }
    private void cargarDatos() {
        modeloTabla.setRowCount(0);
    
        // Obtener la lista de objetos desde el DAO
        List<Object> usuarios = usuariosDAO.getAll();
        
    for(Object usuarioObj : usuarios) {
        if(usuarioObj instanceof UsuariosDTO) {
            UsuariosDTO usuarioDTO = (UsuariosDTO) usuarioObj;
            modeloTabla.addRow(new Object[]{
                usuarioDTO.getId(), 
                usuarioDTO.getUsuario(), 
                usuarioDTO.getNombre(),    
                usuarioDTO.getEmail(),
                usuarioDTO.getContrasena(), // Asegúrate que el nombre del método coincide
                usuarioDTO.getIdRol() ,     // con tu clase UsuariosDTO
                usuarioDTO.getActivo()
            });
        } else if(usuarioObj instanceof Usuarios) {
            Usuarios usuario = (Usuarios) usuarioObj;
            modeloTabla.addRow(new Object[]{
                usuario.getId(), 
                usuario.getUsuario(),
                usuario.getNombre(), 
                usuario.getEmail(),     // Asumiendo que Usuarios tiene estos campos
                usuario.getContrasena(),
                usuario.getRol(),
                usuario.getActivo()
            });
        }
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
